name: Release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact-name: wally-patch-package-win64
            pkg-target: latest-win-x64
          - os: ubuntu-latest
            artifact-name: wally-patch-package-linux
            pkg-target: latest-linux-x64
          - os: macos-latest
            artifact-name: wally-patch-package-macos
            pkg-target: latest-macos-x64
          - os: macos-latest
            artifact-name: wally-patch-package-macos-aarch64
            pkg-target: latest-macos-arm64

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build program
        run: |
          npm run transpile
          npx pkg --no-bytecode --public --targets ${{ matrix.pkg-target }} --public-packages '*' --compress brotli --out-path bin build/app.js
          npm run clean

      - name: Archive files
        shell: bash
        run: |
          mkdir -p staging

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv bin/app.exe staging/wally-patch-package.exe
            cd staging
            7z a ../release.zip *
          else
            mv bin/app staging/wally-patch-package
            cd staging
            zip ../release.zip *
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            artifacts/wally-patch-package-win64/release.zip
            artifacts/wally-patch-package-linux/release.zip
            artifacts/wally-patch-package-macos/release.zip
            artifacts/wally-patch-package-macos-aarch64/release.zip
